// Start of code segment generated by Google Gemini 3.1 Pro

/**
 * Main Engine Class for 2D Sandbox Games
 */
class SandboxEngine {
    constructor(canvasId) {
        this.canvas = document.getElementById(canvasId);
        this.ctx = this.canvas.getContext('2d');
        
        // Camera properties
        this.camera = { x: 0, y: 0, zoom: 1 };
        
        // Input state
        this.input = {
            isDragging: false,
            lastMouseX: 0,
            lastMouseY: 0,
            mouseX: 0,
            mouseY: 0
        };

        // Engine Configuration
        this.config = {
            gridMode: 'free', // 'free', 'rect', 'iso'
            gridSize: 64      // Size of the cell or the cube edge
        };

        this.objects = [];
        
        this.onMouseClick = null;
        this.onRightClick = null;

        this._resize();
        window.addEventListener('resize', () => this._resize());
        this._initInput();
        this._loop();
    }

    _resize() {
        this.canvas.width = window.innerWidth;
        this.canvas.height = window.innerHeight;
    }

    _initInput() {
        this.canvas.addEventListener('mousedown', (e) => {
            if (e.button === 1) { // Middle click for panning
                this.input.isDragging = true;
            } else if (e.button === 0) { // Left click
                const worldCoords = this.screenToWorld(e.clientX, e.clientY);
                if (this.onMouseClick) this.onMouseClick(worldCoords);
            } else if (e.button === 2) { // Right click
                const worldCoords = this.screenToWorld(e.clientX, e.clientY);
                if (this.onRightClick) this.onRightClick(worldCoords);
            }
            this.input.lastMouseX = e.clientX;
            this.input.lastMouseY = e.clientY;
        });

        this.canvas.addEventListener('mousemove', (e) => {
            this.input.mouseX = e.clientX;
            this.input.mouseY = e.clientY;

            if (this.input.isDragging) {
                const dx = e.clientX - this.input.lastMouseX;
                const dy = e.clientY - this.input.lastMouseY;
                this.camera.x += dx / this.camera.zoom;
                this.camera.y += dy / this.camera.zoom;
                this.input.lastMouseX = e.clientX;
                this.input.lastMouseY = e.clientY;
            }
        });

        this.canvas.addEventListener('mouseup', (e) => {
            if (e.button === 1) this.input.isDragging = false;
        });

        this.canvas.addEventListener('contextmenu', e => e.preventDefault());
    }

    /**
     * Converts screen coordinates to world coordinates based on grid mode
     */
    screenToWorld(screenX, screenY) {
        let worldX = (screenX - this.canvas.width / 2) / this.camera.zoom - this.camera.x;
        let worldY = (screenY - this.canvas.height / 2) / this.camera.zoom - this.camera.y;

        const size = this.config.gridSize;

        if (this.config.gridMode === 'rect') {
            worldX = Math.round(worldX / size) * size;
            worldY = Math.round(worldY / size) * size;
        } else if (this.config.gridMode === 'iso') {
            // Convert to isometric grid coordinates
            const halfW = size * Math.cos(Math.PI / 6); // approx 0.866 * size
            const halfH = size * 0.5;

            const gridX = Math.round((worldX / halfW + worldY / halfH) / 2);
            const gridY = Math.round((worldY / halfH - worldX / halfW) / 2);

            // Convert back to world coordinates to get the snapped center
            worldX = (gridX - gridY) * halfW;
            worldY = (gridX + gridY) * halfH;
        }

        return { x: worldX, y: worldY };
    }

    /**
     * Adds an object to the scene
     */
    addObject(obj) {
        this.objects.push(obj);
        // Sort for pseudo-depth based on Y axis (crucial for isometric)
        this.objects.sort((a, b) => a.y - b.y);
    }

    /**
     * Removes an object at specific coordinates
     */
    removeObjectAt(x, y, tolerance = 10) {
        this.objects = this.objects.filter(obj => {
            const dist = Math.sqrt(Math.pow(obj.x - x, 2) + Math.pow(obj.y - y, 2));
            return dist > tolerance;
        });
    }

    /**
     * Draws an Isometric Cube from 3 square textures using Canvas Transform
     * The texture is "folded" into rhombi with 60 and 120 degree angles.
     */
    drawIsoCube(x, y, size, topImg, leftImg, rightImg) {
        const ctx = this.ctx;
        
        // Ensure images are loaded before drawing
        if (!topImg || !topImg.complete) return;

        ctx.save();
        ctx.translate(x, y);

        const w = topImg.width;
        const h = topImg.height;

        // Mathematical scaling to map a square to the isometric rhombus
        const scaleX = size * Math.cos(Math.PI / 6) / w; // Width projection
        const scaleY = size * Math.sin(Math.PI / 6) / h; // Height projection

        // 1. Draw Top Face
        ctx.save();
        // Transform matrix: a (scaleX), b (skewY), c (skewX), d (scaleY), e (translateX), f (translateY)
        ctx.transform(scaleX, scaleY, -scaleX, scaleY, 0, -size);
        ctx.drawImage(topImg, 0, 0, w, h);
        ctx.restore();

        // 2. Draw Left Face
        if (leftImg && leftImg.complete) {
            ctx.save();
            ctx.transform(scaleX, scaleY, 0, size / h, -size * Math.cos(Math.PI / 6), 0);
            ctx.drawImage(leftImg, 0, 0, leftImg.width, leftImg.height);
            ctx.restore();
        }

        // 3. Draw Right Face
        if (rightImg && rightImg.complete) {
            ctx.save();
            ctx.transform(scaleX, -scaleY, 0, size / h, 0, size);
            ctx.drawImage(rightImg, 0, 0, rightImg.width, rightImg.height);
            ctx.restore();
        }

        ctx.restore();
    }

    _loop() {
        // Clear screen
        this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);

        this.ctx.save();
        
        // Apply camera transformations
        this.ctx.translate(this.canvas.width / 2, this.canvas.height / 2);
        this.ctx.scale(this.camera.zoom, this.camera.zoom);
        this.ctx.translate(this.camera.x, this.camera.y);

        // Render objects
        for (const obj of this.objects) {
            if (obj.render) {
                obj.render(this.ctx, this);
            }
        }

        // Draw hover preview (Ghost block)
        const hoverCoords = this.screenToWorld(this.input.mouseX, this.input.mouseY);
        this.ctx.globalAlpha = 0.5;
        this.ctx.fillStyle = 'rgba(255, 255, 255, 0.2)';
        this.ctx.beginPath();
        this.ctx.arc(hoverCoords.x, hoverCoords.y, 5, 0, Math.PI * 2);
        this.ctx.fill();
        this.ctx.globalAlpha = 1.0;

        this.ctx.restore();

        requestAnimationFrame(() => this._loop());
    }
}

// End of code segment generated by Google Gemini 3.1 Pro