// Start of code segment generated by Google Gemini 3.1 Pro

// Helper function to create colored square textures programmatically for testing
function createTexture(color) {
    const canvas = document.createElement('canvas');
    canvas.width = 128;
    canvas.height = 128;
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = color;
    ctx.fillRect(0, 0, 128, 128);
    
    // Add some border to simulate tiles
    ctx.strokeStyle = 'rgba(0,0,0,0.3)';
    ctx.lineWidth = 4;
    ctx.strokeRect(0, 0, 128, 128);
    
    const img = new Image();
    img.src = canvas.toDataURL();
    return img;
}

// Generate textures
const texTop = createTexture('#8bc34a');   // Green grass top
const texLeft = createTexture('#795548');  // Brown dirt left
const texRight = createTexture('#5d4037'); // Darker dirt right

// Initialize Engine
const game = new SandboxEngine('gameCanvas');

// Configure the engine rules
game.config.gridMode = 'iso'; // Set to 'iso' for true isometric hexagonal grid
game.config.gridSize = 64;    // Side length of the cube

// Define what happens when the player clicks
game.onMouseClick = (worldCoords) => {
    // Create a new cube object
    const newCube = {
        x: worldCoords.x,
        y: worldCoords.y,
        render: function(ctx, engine) {
            // Use the engine's built-in isometric cube renderer
            engine.drawIsoCube(this.x, this.y, engine.config.gridSize, texTop, texLeft, texRight);
        }
    };
    
    game.addObject(newCube);
};

// Define what happens on right click (Remove object)
game.onRightClick = (worldCoords) => {
    // Remove object with a tolerance relative to grid size
    game.removeObjectAt(worldCoords.x, worldCoords.y, game.config.gridSize / 2);
};

// End of code segment generated by Google Gemini 3.1 Pro